[tool.poetry]
name = "slickML" 
version = "0.1.0"
description = "toolbox for rapidly developing Data Science solutions"  
authors = ["Trace Smith <tsmith5151@gmail.com>", "Amir Tahmassebi <amir.benny@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7.1" 
numpy = "1.20.3"
pandas = "1.3.2"
scikit-learn = "0.24.2"
seaborn = "0.11.2" 
shap = "0.39.0"
xgboost = "1.4.2"
bayesian-optimization = "1.2.0"
hyperopt = "0.2.5"
glmnet = "2.2.1"

[tool.poetry.dev-dependencies]
jupyterlab = "3.0.16"
ipykernel = "6.0.1"
ipython = "7.25.0"
flake8 = "3.9.2"
black = "21.6b0"
pytest = "^6.2.4"
matplotlib = "^3.4.2"

[tool.black]
line-length=88
target-version=['py37']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.ipynb_checkpoints
  | \.venv
  | _build
  | build
  | dist
  | tests/.*/setup.py
  | Makefile
)/
'''

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"